name: Linting

on:
  pull_request:
    branches:
      - main

jobs:
  linting:
    name: "Markdown linting"
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: "actions/checkout@v2"
      - name: Lint code
        uses: docker://avtodev/markdown-lint:v1
        with:
          args: "**/*.md"
