name: Markdown

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: lint Markdown
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"

      - uses: avto-dev/markdown-lint@v1.5.0
        with:
          args: "**/*.md"
